version: "3"

services:
  persistence:
    image: rpi-docker-persistence
    volumes:
      - /home/pi/data/rpi-docker-lab/rpi-docker-lab.sqlite:/sqlite_data/sqlite.db
    ports:
      - 8082:8082
    networks:
      - rpi-docker-lab
networks:
  rpi-docker-lab:


